@startuml

package SSC {
   actor "Front Line" as SSC_FL
   actor "Counter" as SSC_CNT
}

actor Cadet as CDT

rectangle Dispatch {
   usecase "Start" as DISPATCH_START
   usecase "Box Assignment" as BOX_ASSIGNMENT
   usecase "\n{{\nsalt\n{+\nBox Id | "Box # (Pre-Assigned)"\nRank | ^Rank List^\nFirst Name| "First Name"\nLast Name | "Last Name"\n[SUBMIT]\n}\n}}" as CADET_FORM
   usecase "Assign Location" as LOCATION_ASSIGNMENT
   usecase "\n{{\nsalt\n{+<b>Contact Information</b>\nLocation Name | <Business Name>\nAddress | <Address>\nSSC Phone | <SSC Phone Number>\n}\n}}" as DISPATCH_CONTACT

   usecase "End" as DISPATCH_END
   
   CDT --> DISPATCH_START
   SSC_FL --> DISPATCH_START
   DISPATCH_START -down-> BOX_ASSIGNMENT
   BOX_ASSIGNMENT --> CADET_FORM
   CADET_FORM --> LOCATION_ASSIGNMENT
   LOCATION_ASSIGNMENT --> DISPATCH_CONTACT
   DISPATCH_CONTACT --> DISPATCH_END

   note left of DISPATCH_START
      Each Box will have QR code printed
      uniquely identify each box
   end note

   note left of BOX_ASSIGNMENT
      Cadet scan the QR code on the box
      and fill in the Google form
   end note
   
   note left of LOCATION_ASSIGNMENT
      After Cadet submit the form
      SSC Staff assign location
      SSC Staff scan 2nd QR code and enter location information to Google Form
      SSC Staff provide location and contact infomration to Cadet
   end note
   
   note left of DISPATCH_CONTACT
      This information should be pre-print before tagging and
      hand out to cadet when the location is assigned
   end note
}

rectangle Tagging {
   usecase "Tagging at Location" as TAG
}

CDT --> TAG

rectangle Return {
   usecase "Start" AS COLLECTION_START
   usecase "Box Return" as BOX_RETURN
   usecase "Count" as COLLECTION_COUNT
   usecase "\n{{\nsalt\n{+in Excel\nBox Id | "Box # (Pre-Assigned)"\nLocation | ^Location List^\n Amount | "$$ Amount"\n[SUBMIT]\n}\n}}" as RETURN_SSC_FORM
   usecase "End" as COLLECTION_END
   
   CDT --> COLLECTION_START
   SSC_FL --> COLLECTION_START
   COLLECTION_START -down-> BOX_RETURN
   BOX_RETURN --> COLLECTION_COUNT
   SSC_CNT --> COLLECTION_COUNT
   COLLECTION_COUNT --> RETURN_SSC_FORM
   RETURN_SSC_FORM --> COLLECTION_END

   note right of BOX_RETURN
      SSC Staff to retrieve the 2nd QR code correspond to the box
      SSC Staff collect fund into the bag and apply QR code to the bag
   end note
   
   note right of COLLECTION_COUNT
      SSC Counter count the fund and write on the list with QR Code 
      SSC Staff looks up box # and enter the amount into Google Form
   end note
}

@enduml
