@startuml

package SSC {
   actor "Front Line" as SSC_FL
   actor "Counter" as SSC_CNT
}

actor Cadet as CDT

CDT --> Tagging

rectangle Dispatch {
   usecase "Start" as DISPATCH_START
   usecase "Box Form" as BOX_FORM
   usecase "\n{{\nsalt\n{+<b>Google Form</b>\nBox ID | "Box ID"\nRank | ^Rank List^\nFirst Name| "First Name"\nLast Name | "Last Name"\nShift | ^AM/PM/AM and PM^\nLocation | ^Location Name^\n[SUBMIT]\n}\n}}" as BOX_FORM
   usecase "\n{{\nsalt\n{+<b>Contact Information</b>\nLocation Name | <Business Name>\nAddress | <Address>\nSSC Phone | <SSC Phone Number>\nOn-Site Supervisor | <Supervisor Name>\n}\n}}" as LOCATION_ASSIGNMENT

   usecase "End" as DISPATCH_END
   
   CDT --> DISPATCH_START
   SSC_FL --> DISPATCH_START
   DISPATCH_START -down-> LOCATION_ASSIGNMENT
   LOCATION_ASSIGNMENT --> BOX_FORM
   BOX_FORM --> DISPATCH_END

   note left of BOX_FORM
      Cadet fills in the google form
      Option 1: (with phone) scan QR code posted on wall
      Option 2: (without phone) fill in google form on laptop
   end note
   
   note left of LOCATION_ASSIGNMENT
      SSC Staff 
      1. assign location and 
      2. provide location slip to Cadet
      This information should be pre-printed before tagging and 
      hand out to cadet when the location is assigned
   end note
   
   note left of DISPATCH_END
      Cadets meet with CJCR/Supervisor before leaving
   end note


}

rectangle Tagging {
   usecase "Tagging at Location" as TAG
}


rectangle Return {
   usecase "Start" AS COLLECTION_START
   usecase "Count" as COLLECTION_COUNT
   usecase "Input" as DATA_INPUT
   usecase "End" as COLLECTION_END
   usecase "Shift End" as SHIFT_END
   usecase "\n{{\nsalt\n{+<b>Return Slip</b>\nBox ID | "Box ID"\nShift | "AM/PM/AM and PM"\nAmount | "$$Amount"\n}\n}}" as BOX_RETURN
   
   BOX_FORM.BOX_RETURN : Failure Mode\nBox ID
   
   CDT --> COLLECTION_START
   SSC_FL --> COLLECTION_START
   COLLECTION_START -down-> BOX_RETURN
   BOX_RETURN --> SHIFT_END
   BOX_RETURN --> COLLECTION_COUNT
   SSC_CNT --> COLLECTION_COUNT
   COLLECTION_COUNT --> DATA_INPUT
   DATA_INPUT --> COLLECTION_END

   note right of BOX_RETURN
      SSC Staff 
      1. unlock the box
      2. put $ into ziplock bag
      3. write down the box id and circle the shift on pre-printed slip
   end note
   
   note right of COLLECTION_COUNT
      SSC Counter
      1. count the fund and 
      2. write the amount on the Return Slip inside the bag
   end note
   
   note right of DATA_INPUT
      SSC Counter/Staff
      1. look up box # in the Google Sheet and 
      2. enter the amount according to the Box ID
   end note
   
   note right of SHIFT_END
      Cadet must lock and secure the box for the next shift
   end note
}

@enduml
