@startuml

rectangle SSC {
   actor "Front Line" as SSC_FL
   actor "Counter" as SSC_CNT
}

actor Cadet as CDT

rectangle Dispatch {
   usecase "Start" as DISPATCH_START
   usecase "Box Assignment" as BOX_ASSIGNMENT
   usecase "Assign Location" as LOCATION_ASSIGNMENT
   usecase "\n{{\nsalt\n{+<b>Contact Information</b>\nLocation Name | <Business Name>\nAddress | <Address>\nSSC Phone | <SSC Phone Number>\n}\n}}" as DISPATCH_CONTACT
   usecase "End" as DISPATCH_END
   
   CDT --> DISPATCH_START
   SSC_FL --> DISPATCH_START
   
   DISPATCH_START -down-> BOX_ASSIGNMENT
   BOX_ASSIGNMENT --> LOCATION_ASSIGNMENT
   DISPATCH_CONTACT --> LOCATION_ASSIGNMENT
   LOCATION_ASSIGNMENT --> DISPATCH_END

   note left of DISPATCH_START
      Each Box will have 2 QR code printed
      uniquely identify each box
   end note

   note left of BOX_ASSIGNMENT
      Cadet scan the QR code on the box
      and fill in the Google form
   end note
   
   note left of LOCATION_ASSIGNMENT
      After Cadet submit the form
      SSC Staff assign location
      SSC Staff scan 2nd QR code and enter location information to Google Form
      SSC Staff provide location and contact infomration to Cadet
   end note
   
   note top of DISPATCH_CONTACT
      This information should be pre-print before tagging and
      hand out to cadet when the location is assigned
   end note
}

rectangle Tagging {
   usecase "Tagging at Location" as TAG
}

CDT --> TAG

interface "QR Box" as GAPP_QR_BOX
interface "QR Label" as GAPP_QR_SSC

component GAPP {
   portin GAPP_CADET_FORM_URL
   portin GAPP_SSC_FORM_URL
   
   component "\n{{\nsalt\n{+\nBox Id | "Box #"\nRank | ^Rank List^\nFirst Name | "First Name"\nLast Name | "Last Name"\n[SUBMIT]\n}\n}}" as GAPP_FORM_CADET
   component "\n{{\nsalt\n{+\nBox Id | "Box #"\nLocation | ^Location List^\n Amount | "$$ Amount"\n[SUBMIT]\n}\n}}" as GAPP_FORM_SSC
   
   database "Google Sheet" {
      component "{{\nrecord "Cadet Data" {\n-BoxId\n-ShiftId\n-Rank\n-First Name\n-Last Name\n}\n}}" as CadetData
      component "{{\nrecord "SSC Data" {\n-BoxId\n-ShiftId\n-Location\n-Amount\n}\n}}" as SSCData 
      component MasterDataSheet
   }
   
   GAPP_CADET_FORM_URL -- GAPP_FORM_CADET
   GAPP_SSC_FORM_URL -- GAPP_FORM_SSC
   GAPP_FORM_CADET --> CadetData
   GAPP_FORM_SSC --> SSCData
   CadetData --> MasterDataSheet
   SSCData --> MasterDataSheet
   
}

rectangle Return {
   usecase "Start" AS COLLECTION_START
   usecase "Box Return" as BOX_RETURN
   usecase "Count" as COLLECTION_COUNT
   usecase "End" as COLLECTION_END
   
   CDT --> COLLECTION_START
   SSC_FL --> COLLECTION_START
   COLLECTION_START -down-> BOX_RETURN
   BOX_RETURN --> COLLECTION_COUNT
   SSC_CNT --> COLLECTION_COUNT
   COLLECTION_COUNT --> COLLECTION_END

   note right of BOX_RETURN
      SSC Staff to retrieve the 2nd QR code correspond to the box
      SSC Staff collect fund into the bag and apply QR code to the bag
   end note
   
   note right of COLLECTION_COUNT
      SSC Counter Counts the fund and write on the QR Code label
      SSC Counter/Staff scan 2nd QR code and enter the amount into Google Form
   end note
}

BOX_ASSIGNMENT ..> GAPP_QR_BOX : use
LOCATION_ASSIGNMENT ..> GAPP_QR_SSC : use
COLLECTION_COUNT ..> GAPP_QR_SSC : use
GAPP_QR_BOX -- GAPP_CADET_FORM_URL
GAPP_QR_SSC -- GAPP_SSC_FORM_URL

@enduml
